import json
from datetime import datetime

# Mock the data structure that will be uploaded to MongoDB
timestamp_ms = int(datetime.now().timestamp() * 1000)

example_card = {
    'booster': 'UA01ST',
    'cardId': 'CGH-1-015',
    'card_name': 'ルルーシュ・ランペルージ',
    'rarity': 'U',
    'product_link': '/shopdetail/000000030403/ua/page1/recommend/',
    'price_history': {
        str(timestamp_ms): {
            'price': 30,
            'stock': 15
        }
    }
}

# This is what will be sent to MongoDB
mongodb_document = {
    # _id is auto-generated by MongoDB
    'booster': example_card['booster'],
    'cardId': example_card['cardId'],
    'rarity': example_card['rarity'],
    'card_name': example_card['card_name'],
    'product_link': example_card['product_link'],
    'price_history': example_card['price_history'],
    'created_at': timestamp_ms,  # Set on INSERT only
    'last_updated': timestamp_ms  # Updated on every scrape
}

print("=" * 80)
print("📦 MongoDB Document Structure for Fulla Ahead")
print("=" * 80)
print(f"\nCollection: geekstack.cardprices_fulla\n")
print(json.dumps(mongodb_document, indent=2, ensure_ascii=False))

print("\n" + "=" * 80)
print("Comparison with Yuyutei structure:")
print("=" * 80)

yuyutei_doc = {
    "rarity": "SR★★★",
    "cardId": "EX13BT",
    "booster": "GIM-2-029",
    "card_name": "花海 咲季(パラレル/特別仕様)",
    "product_link": "https://yuyu-tei.jp/sell/ua/card/gim2/10050",
    "price_history": {
        "1773662275172": {
            "price": 59800,
            "stock": 0
        }
    },
    "created_at": 1773662275172,
    "last_updated": 1773662275172
}

print("\nYuyutei structure:")
print(json.dumps(yuyutei_doc, indent=2))

print("\n✅ Structure matches! Same fields:")
print("  - booster")
print("  - cardId")
print("  - rarity")
print("  - card_name")
print("  - product_link")
print("  - price_history (with timestamp key and price/stock values)")
print("  - created_at (timestamp in milliseconds)")
print("  - last_updated (timestamp in milliseconds)")
