COLOR_MAP = {
    "黄": "yellow",
    "赤": "red",
    "青": "blue",
    "緑": "green",
    "無": "colorless"
}

CATEGORY_MAP = {
    "キャラクター": "character",
    "フィールド": "field",
    "イベント": "event",
}

TRIGGER_MAP = {
    "draw": "Draw a card.",
    "get": "Add this card to your hand.",
    "raid": "Add this to hand or Raid it if you have the required energy.",
    "active": "Active 1 of your character and give it +3000BP.",
    "special": "Choose one of your opponent's Front Line characters and retire it.",
    "final": "If you have no life, place the top card of your deck into your life area.",
    "color_yellow": "Choose 1 character on your opponent's front line and rest it. The next time it becomes active, it doesn't.",
    "color_red": "Choose one of your opponent's Front Line characters with BP2500 or less and retire it.",
    "color_blue": "Choose one of your opponent's Front Line characters with BP3500 or less, and return it to their hand.",
    "color_green": "Play 1 Green Character Card with required energy of 2 or less and AP 1 from your hand to your area and set it to active.",
    "color_purple": "Play a purple character with 2 Energy cost or less and 1 AP from Outside Area to your Front Line in Active.",
    "-" : "-"
}

TRIGGER_STATE_MAP = {
    "カードを1枚引く。" : "draw",
    "このカードを手札に加える。" : "get",
    "このカードを手札に加えるか、必要エナジーを満たしている場合、レイドさせる。" : "raid",
    "自分の場のキャラを1枚選び、アクティブにし、このターン中、BP+3000。" : "active",
    "相手のフロントLのキャラを1枚選び、退場させる。" : "special",
    "自分のライフが無い場合、自分の山札の上から1枚を自分のライフエリアに置く。":"final",
    "相手のフロントLのキャラを1枚選び、レストにする。それは次の1回アクティブにならない。" : "color_yellow",
    "BP2500以下の相手のフロントLのキャラを1枚選び、退場させる。" : "color_red",
    "BP3500以下の相手のフロントLのキャラを1枚選び、手札に戻す。" : "color_blue",
    "自分の手札から必要エナジーが2以下で消費APが1の緑のキャラカードを1枚自分の場にアクティブで登場させる。" : "color_green",
    "自分の場外から必要エナジーが2以下で消費APが1の紫のキャラカードを1枚自分のフロントLにアクティブで登場させる。" : "color_purple",
    "-" : "-"

}

UATAG_MAP = {
  'インパクト（1）': '[Impact 1]',
  'インパクト（2）': '[Impact 2]',
  'インパクト（3）': '[Impact 3]',
  'インパクト（4）': '[Impact 4]',
  'インパクト': '[Impact]',
  '2回ブロック': '[Block x2]',
  '2回アタック': '[Attack x2]',
  '狙い撃ち': '[Snipe]',
  'インパクト（+1）': '[Impact +1]',
  'ステップ': '[Step]',
  'ダメージ': '[Damage]',
  'ダメージ（+1）': '[Damage +1]',
  'ダメージ（2）': '[Damage 2]',
  'ダメージ（3）': '[Damage 3]',
  'ダメージ（4）': '[Damage 4]',
  'ダメージ（5）': '[Damage 5]',
  'ダメージ（6）': '[Damage 6]',
  'ダメージ（7）': '[Damage 7]',
  'インパクト無効': '[Impact Negate]',
  'ターン1': '[Once Per Turn]',
  'レストにする': '[Rest this card]',
  'このカードを退場させる': '[Retire this card]',
  '手札を1枚場外に置く': '[Place 1 card from hand to Outside Area]',
  '手札を2枚場外に置く': '[Place 2 cards from hand to Outside Area]',
  '手札を3枚場外に置く': '[Place 3 cards from hand to Outside Area]',
  'フロントLにある場合': '[When In Front Line]',
  'エナジーLにある場合': '[When In Energy Line]',
  '場外にある場合': '[When In Outside Area]',
  '除外エリアにある場合': '[When In Remove Area]',
  'APを1支払う': '[Pay 1 AP]',
  'レイド': '[Raid]',
  '登場時': '[On Play]',
  '退場時': '[On Retire]',
  'ブロック時': '[When Blocking]',
  '起動メイン': '[Activate Main]',
  'アタック時': '[When Attacking]',
  '自分のターン中': '[Your Turn]',
  '/icons/UAtags/CTOppTurn.png': "[Opponent's Turn]",
  'トリガー': '[Trigger]',
}

ANIME_MAP = {
    "UNION ARENA": "UNION ARENA",
    "コードギアス 反逆のルルーシュ": "Code Geass: Lelouch of the Rebellion",
    "呪術廻戦": "Jujutsu Kaisen",
    "HUNTER×HUNTER": "Hunter x Hunter",
    "アイドルマスター シャイニーカラーズ": "The Idolmaster Shiny Colors",
    "鬼滅の刃": "Demon Slayer",
    "Tales of ARISE": "Tales of Arise",
    "転生したらスライムだった件": "That Time I Got Reincarnated as a Slime",
    "BLEACH 千年血戦篇": "Bleach: Thousand-Year Blood War",
    "僕とロボコ": "Me & Roboco",
    "僕のヒーローアカデミア": "My Hero Academia",
    "銀魂": "Gintama",
    "ブルーロック": "Blue Lock",
    "鉄拳7": "Tekken 7",
    "Dr.STONE": "Dr. Stone",
    "ソードアート・オンライン": "Sword Art Online",
    "SYNDUALITY Noir": "SYNDUALITY Noir",
    "トリコ": "Toriko",
    "勝利の女神：NIKKE": "Goddess of Victory: Nikke",
    "ハイキュー‼": "Haikyu!!",
    "ブラッククローバー": "Black Clover",
    "幽☆遊☆白書": "Yu Yu Hakusho",
    "GAMERA -Rebirth-": "Gamera -Rebirth-",
    "進撃の巨人": "Attack on Titan",
    "SHY": "SHY",
    "アンデッドアンラック": "Undead Unluck",
    "君のことが大大大大大好きな100人の彼女": "The 100 Girlfriends Who Really, Really, Really, Really, Really Love You",
    "学園アイドルマスター": "Gakuen Idolmaster",
    "怪獣８号": "Kaiju No. 8",
    "仮面ライダー": "Kamen Rider",
    "アークナイツ": "Arknights",
    "魔法少女まどか☆マギカ": "Puella Magi Madoka Magica",
    "シャングリラ・フロンティア": "Shangri-La Frontier",
    "2.5次元の誘惑": "2.5 Dimensional Seduction",
    "コードギアス 奪還のロゼ": "Code Geass: Rozé of the Recapture",
    "ワンパンマン": "One Punch Man",
    "マクロス": "Macross",
    "WIND BREAKER": "Wind Breaker",
    "鋼の錬金術師": "Fullmetal Alchemist",
    "キン肉マン": "Kinnikuman",
    "Re:ゼロから始める異世界生活": "Re:Zero - Starting Life in Another World",
    "るろうに剣心 －明治剣客浪漫譚－": "Rurouni Kenshin: Meiji Swordsman Romantic Story",
    "〈物語〉シリーズ": "Monogatari Series",
    "SAKAMOTO DAYS": "Sakamoto Days",
    "ヱヴァンゲリヲン新劇場版": "Evangelion: New Theatrical Edition",
    "To LOVEる-とらぶる-": "To Love-Ru",
    "カグラバチ": "Kagurabachi",
    "東京喰種トーキョーグール": "Tokyo Ghoul",
    "キングダム": "Kingdom",
    "魔都精兵のスレイブ": "Chained Soldier",
    "俺だけレベルアップな件": "Solo Leveling"
}